apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-doc-gen
  labels:
    app: camunda-doc-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-doc-gen
  template:
    metadata:
      labels:
        app: camunda-doc-gen
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: camunda-doc-gen
        image: docker.io/abdosblz/camunda-doc-gen:3
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
