apiVersion: v1
kind: Service
metadata:
  name: camunda-doc-gen
  labels:
    app: camunda-doc-gen
spec:
  selector:
    app: camunda-doc-gen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP