apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-doc-gen-backend
  labels:
    app: camunda-doc-gen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-doc-gen-backend
  template:
    metadata:
      labels:
        app: camunda-doc-gen-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: camunda-doc-gen-backend
        image: docker.io/abdosblz/camunda-doc-gen-backend:4
        ports:
        - containerPort: 8080
