apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camunda-doc-gen
  annotations:
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: camunda-doc-gen.example.com # TODO: Replace with your actual hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-doc-gen
            port:
              number: 80
  # tls: # Uncomment to enable TLS
  # - hosts:
  #   - camunda-doc-gen.example.com
  #   secretName: camunda-doc-gen-tls
