apiVersion: v1
kind: Service
metadata:
  name: camunda-doc-gen-backend
spec:
  selector:
    app: camunda-doc-gen-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
